In [35]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [36]:
import cv2
import numpy as np
from utils import *
from frame import extract,match,Frame


In [37]:
W,H=640,480
K=np.array([[1,0,W//2],[0,1,H//2],[0,0,1]])

In [38]:
frames=[]

In [41]:

def process_img(img,depth):

    frame=Frame(img,depth,K)
    frames.append(frame)


    if len(frames)<=1:
        return
    f_c=frames[-1] #current frame
    f_p=frames[-2] # previous frame
    ret,pose=match(f_p,f_c)

    # pose relative transformation of current frame  
    # with respect to previous frame 

    if ret is None:
        return
    
    if pose is None:
        return
    


    f_c.pose=np.dot(pose,f_p.pose)
    print(f_c.pose)

    pts4d=add_ones(f_c.pts)
    pts4d=np.dot(f_p.pose,pts4d.T)


    for kp1,kp2 in ret:
        u_p,v_p,_=denormalize(kp1,f_p.K)
        u_c,v_c,_=denormalize(kp2,f_c.K)

        cv2.circle(img,(u_p,v_p),color=(0,255,0),radius=3)
        cv2.line(img,(u_p,v_p),(u_c,v_c),color=(255,0,0))
    disp(img,"RGB")




In [42]:
if __name__ == "__main__":
    
    depth_paths='../dataset/rgbd_dataset_freiburg1_xyz/depth.txt'
    dlist=data(depth_paths)

    rgb_paths='../dataset/rgbd_dataset_freiburg1_xyz/rgb.txt'
    ilist=data(rgb_paths)

    dataset_path='../dataset/rgbd_dataset_freiburg1_xyz/'
    

    for i in range(len(dlist)):

        frame=cv2.imread(dataset_path+ilist[i])
        depth=cv2.imread(dataset_path+dlist[i],0)
        # print(frame.shape,depth.shape)
        W=frame.shape[1]
        H=frame.shape[0]
        # print(W,H)
        process_img(frame,depth)
        # print(frame)

        if frame is None:
            print("End of frame")
            break

        
        disp(depth,"Depth")
        
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    cv2.destroyAllWindows()


        


[[ 1.00948764e+00  1.81088718e-02 -1.27051012e-02  2.81165615e+00]
 [-1.80867671e-02  1.00956626e+00  1.86839176e-03 -2.24299146e+00]
 [ 1.27365494e-02 -1.64036347e-03  1.00964833e+00  1.01324735e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 1.01559722e+00  1.48234719e-02 -1.28567015e-02  7.71133401e+00]
 [-1.48036753e-02  1.01567753e+00  1.65640716e-03 -7.34298283e+00]
 [ 1.28794912e-02 -1.46872959e-03  1.01570404e+00  8.40941805e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 1.02454613e+00  1.26553005e-02 -1.30170402e-02  1.13951720e+01]
 [-1.26420782e-02  1.02462836e+00  1.12065425e-03 -1.40620984e+01]
 [ 1.30298820e-02 -9.59883719e-04  1.02462367e+00  5.97982290e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 1.03546257e+00  1.44638664e-02 -1.25604385e-02  1.48585042e+01]
 [-1.44915101e-02  1.03553604e+00 -2.19430424e-03 -1.96705082e+01]
 [ 1.25285346e-02  2.36968464e-03  1.03556126e+00 -1.720073

/media/sujan/Work/One_Folder/Visual_SLAM/RGBD_SLAM/Implementation/transformation.py:44: RuntimeWarning: divide by zero encountered in scalar divide
  c=(1/var_x)*(np.trace(D*S))
/media/sujan/Work/One_Folder/Visual_SLAM/RGBD_SLAM/Implementation/transformation.py:44: RuntimeWarning: invalid value encountered in scalar multiply
  c=(1/var_x)*(np.trace(D*S))
/media/sujan/Work/One_Folder/Visual_SLAM/RGBD_SLAM/Implementation/transformation.py:47: RuntimeWarning: invalid value encountered in scalar divide
  error=var_y-((np.trace(D*S))**2)/var_x


[[ 1.15297283e+00 -1.74716835e-01  3.60912699e-03 -1.86975742e+02]
 [ 1.74718178e-01  1.15200156e+00 -4.74481359e-02 -2.22246343e+01]
 [ 3.54354013e-03  4.74530791e-02  1.16516994e+00 -4.14322596e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 1.15942322e+00 -1.79137663e-01  4.09168259e-03 -1.95255293e+02]
 [ 1.79154086e-01  1.15843224e+00 -4.80396611e-02 -1.52649304e+01]
 [ 3.29510426e-03  4.81008648e-02  1.17219653e+00 -4.29529822e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 1.16437879e+00 -1.76604119e-01  4.19218604e-03 -2.01117835e+02]
 [ 1.76626701e-01  1.16338173e+00 -4.82755911e-02 -7.26773097e+00]
 [ 3.09802671e-03  4.83581363e-02  1.17670576e+00 -4.38408861e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 1.16728220e+00 -1.70150913e-01  3.88434318e-03 -2.04110462e+02]
 [ 1.70166810e-01  1.16629108e+00 -4.81928190e-02 -1.98757864e+00]
 [ 3.11097058e-03  4.82489149e-02  1.17863333e+00 -4.422761