In [173]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [183]:
import cv2
import numpy as np
from utils import *
from extractor import Extractor
import matplotlib.pyplot as plt
from transformation import *
from ransac import *


In [184]:
fe=Extractor()

In [187]:

def process_img(img,depth):
    matches,pose=fe.extract(img,depth)


    print(pose)
    if pose is None:
        return
    if matches is None:
        return
    # ransac(matches)
    # print(matches[:-1][0])
    
    # projected_map(matches,depth)
    for kp1,kp2 in matches:
        u1,v1,_=map(lambda x: int(round(x)),kp1)
        u2,v2,_=map(lambda x: int(round(x)),kp2)
        cv2.circle(img,(u1,v1),color=(0,255,0),radius=3)
        cv2.line(img,(u1,v1),(u2,v2),color=(255,0,0))
        disp(img,"RGB")




In [188]:
if __name__ == "__main__":
    
    depth_paths='../rgbd_dataset_freiburg1_xyz/depth.txt'
    dlist=data(depth_paths)

    rgb_paths='../rgbd_dataset_freiburg1_xyz/rgb.txt'
    ilist=data(rgb_paths)

    dataset_path='../rgbd_dataset_freiburg1_xyz/'
    

    for i in range(len(dlist)):

        frame=cv2.imread(dataset_path+ilist[i])
        depth=cv2.imread(dataset_path+dlist[i],0)
        # print(frame.shape,depth.shape)


        process_img(frame,depth)
        # print(frame)

        if frame is None:
            print("End of frame")
            break

        
        disp(depth,"Depth")
        
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    cv2.destroyAllWindows()


        


[[ 1.15871398e+00  9.30511304e-04  1.47706026e-01 -3.55408568e+01]
 [ 8.85881447e-03  1.16552715e+00 -7.68375447e-02 -1.02275099e+02]
 [-1.47443065e-01  7.73409401e-02  1.15616389e+00  1.40943838e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 9.94394442e-01 -9.39815815e-05 -6.35683176e-05 -2.59688097e+00]
 [ 9.39820055e-05  9.94394444e-01  6.62890934e-06  6.85107086e+00]
 [ 6.35676908e-05 -6.63491726e-06  9.94394446e-01  5.76410454e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 9.90529921e-01  8.72687204e-04  2.29884599e-05 -1.22114272e+00]
 [-8.72697141e-04  9.90529827e-01  4.31720594e-04  8.84699040e+00]
 [-2.26080899e-05 -4.31740680e-04  9.90530211e-01  3.62081633e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 9.91900529e-01  1.75143489e-03 -1.83920226e-05 -1.72491935e+00]
 [-1.75143319e-03  9.91900525e-01  9.13097228e-05  7.95885227e+00]
 [ 1.85532225e-05 -9.12771051e-05  9.91902071e-01  1.789964